---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseParameterName:
        enabled: true
        exclude_paths:
        - src/Phug/Renderer/Adapter/
      Design/EvalExpression:
        enabled: true
        exclude_paths:
        - src/Phug/Renderer/Adapter/EvalAdapter.php
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
- src/Phug/Renderer/Adapter/Stream/
