
language: php

git:
    depth: 5

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

matrix:
    include:
        - php: hhvm
          dist: trusty
          sudo: required

install:
    - travis_retry composer self-update
    - travis_retry composer install

script:
    - vendor/bin/phpunit -c vendor/phug/dev-tool/config --debug

notifications:
    slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
    code_climate:
        repo_token: a2adfbf99ea6d5f8e89d5b2a2ab3e58dd6b52ccf32c047bdead69da2970fc5ab
